title: Football-Analytics
description: Football-Analytics is a GitHub repository, contains code which uses statsbomb's open data and builds a bunch of visualizations
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
